services:
  redis:
    image: redis
    ports:
      - "6379"

  db: 
    image: postgres:9.4
    hostname: db

  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports: 
      - 5000:80
    depends_on:
      - redis

  result:
    image: dockersamples/examplevotingapp_result:before
    container_name: result
    ports:
     - 5001:80

  worker:
    image: dockersamples/examplevotingapp_worker